name: docker-compose-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

permissions:
    contents: write
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
    # continue-on-error: true
    # mkdir -p dist && \
      - name: set permission and run
        run: |
          sudo chmod -R 777 . && \
          ls && \
          docker compose up --build && docker compose down
          
      # - uses: fastai/workflows/ssh@master
      #   with:
      #     ssh_key: ${{ secrets.SSH_KEY }}
      #     key_file: id_ecdsa
          
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@master

      - working-directory: 'project'
        run: |
          ls -R
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "project"
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "project/${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
